// Generated by scripts/import-f1-ics.mjs. Do not edit manually.
export const F1_SEASON_2026 = {
  "schemaVersion": 1,
  "season": 2026,
  "source": "f1calendar.com",
  "sourceUpdatedAt": "2026-07-27T01:56:46Z",
  "rounds": [
    {
      "round": 1,
      "id": "australia",
      "name": {
        "zh": "澳大利亚大奖赛",
        "en": "Australian Grand Prix"
      },
      "location": {
        "zh": "墨尔本",
        "en": "Melbourne"
      },
      "coordinates": {
        "latitude": -37.8373,
        "longitude": 144.9666
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP0_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-03-06T01:30:00Z",
          "endsAt": "2026-03-06T02:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP0_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-03-06T05:00:00Z",
          "endsAt": "2026-03-06T06:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP0_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-03-07T01:30:00Z",
          "endsAt": "2026-03-07T02:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP0_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-03-07T05:00:00Z",
          "endsAt": "2026-03-07T06:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP0_2026_gp",
          "type": "race",
          "startsAt": "2026-03-08T04:00:00Z",
          "endsAt": "2026-03-08T06:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 2,
      "id": "china",
      "name": {
        "zh": "中国大奖赛",
        "en": "Chinese Grand Prix"
      },
      "location": {
        "zh": "上海",
        "en": "Shanghai"
      },
      "coordinates": {
        "latitude": 31.3807,
        "longitude": 121.2498
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP1_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-03-13T03:30:00Z",
          "endsAt": "2026-03-13T04:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP1_2026_sprintQualifying",
          "type": "sprint-qualifying",
          "startsAt": "2026-03-13T07:30:00Z",
          "endsAt": "2026-03-13T08:15:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP1_2026_sprint",
          "type": "sprint",
          "startsAt": "2026-03-14T03:00:00Z",
          "endsAt": "2026-03-14T03:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP1_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-03-14T07:00:00Z",
          "endsAt": "2026-03-14T08:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP1_2026_gp",
          "type": "race",
          "startsAt": "2026-03-15T07:00:00Z",
          "endsAt": "2026-03-15T09:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 3,
      "id": "japan",
      "name": {
        "zh": "日本大奖赛",
        "en": "Japanese Grand Prix"
      },
      "location": {
        "zh": "铃鹿",
        "en": "Suzuka"
      },
      "coordinates": {
        "latitude": 34.8448408,
        "longitude": 136.5334551
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP2_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-03-27T02:30:00Z",
          "endsAt": "2026-03-27T03:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP2_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-03-27T06:00:00Z",
          "endsAt": "2026-03-27T07:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP2_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-03-28T02:30:00Z",
          "endsAt": "2026-03-28T03:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP2_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-03-28T06:00:00Z",
          "endsAt": "2026-03-28T07:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP2_2026_gp",
          "type": "race",
          "startsAt": "2026-03-29T05:00:00Z",
          "endsAt": "2026-03-29T07:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 4,
      "id": "miami",
      "name": {
        "zh": "迈阿密大奖赛",
        "en": "Miami Grand Prix"
      },
      "location": {
        "zh": "迈阿密",
        "en": "Miami"
      },
      "coordinates": {
        "latitude": 25.957764,
        "longitude": -80.238835
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP3_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-05-01T16:00:00Z",
          "endsAt": "2026-05-01T17:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP3_2026_sprintQualifying",
          "type": "sprint-qualifying",
          "startsAt": "2026-05-01T20:30:00Z",
          "endsAt": "2026-05-01T21:15:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP3_2026_sprint",
          "type": "sprint",
          "startsAt": "2026-05-02T16:00:00Z",
          "endsAt": "2026-05-02T16:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP3_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-05-02T20:00:00Z",
          "endsAt": "2026-05-02T21:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP3_2026_gp",
          "type": "race",
          "startsAt": "2026-05-03T17:00:00Z",
          "endsAt": "2026-05-03T19:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 5,
      "id": "canada",
      "name": {
        "zh": "加拿大大奖赛",
        "en": "Canadian Grand Prix"
      },
      "location": {
        "zh": "蒙特利尔",
        "en": "Montreal"
      },
      "coordinates": {
        "latitude": 45.5034,
        "longitude": -73.5267
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP4_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-05-22T16:30:00Z",
          "endsAt": "2026-05-22T17:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP4_2026_sprintQualifying",
          "type": "sprint-qualifying",
          "startsAt": "2026-05-22T20:30:00Z",
          "endsAt": "2026-05-22T21:15:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP4_2026_sprint",
          "type": "sprint",
          "startsAt": "2026-05-23T16:00:00Z",
          "endsAt": "2026-05-23T16:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP4_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-05-23T20:00:00Z",
          "endsAt": "2026-05-23T21:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP4_2026_gp",
          "type": "race",
          "startsAt": "2026-05-24T20:00:00Z",
          "endsAt": "2026-05-24T22:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 6,
      "id": "monaco",
      "name": {
        "zh": "摩纳哥大奖赛",
        "en": "Monaco Grand Prix"
      },
      "location": {
        "zh": "蒙特卡洛",
        "en": "Monte Carlo"
      },
      "coordinates": {
        "latitude": 43.7338,
        "longitude": 7.4215
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP5_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-06-05T11:30:00Z",
          "endsAt": "2026-06-05T12:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP5_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-06-05T15:00:00Z",
          "endsAt": "2026-06-05T16:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP5_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-06-06T10:30:00Z",
          "endsAt": "2026-06-06T11:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP5_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-06-06T14:00:00Z",
          "endsAt": "2026-06-06T15:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP5_2026_gp",
          "type": "race",
          "startsAt": "2026-06-07T13:00:00Z",
          "endsAt": "2026-06-07T15:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 7,
      "id": "barcelona-catalunya",
      "name": {
        "zh": "巴塞罗那-加泰罗尼亚大奖赛",
        "en": "Barcelona-Catalunya Grand Prix"
      },
      "location": {
        "zh": "巴塞罗那",
        "en": "Barcelona"
      },
      "coordinates": {
        "latitude": 41.5638,
        "longitude": 2.2585
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP6_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-06-12T11:30:00Z",
          "endsAt": "2026-06-12T12:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP6_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-06-12T15:00:00Z",
          "endsAt": "2026-06-12T16:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP6_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-06-13T10:30:00Z",
          "endsAt": "2026-06-13T11:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP6_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-06-13T14:00:00Z",
          "endsAt": "2026-06-13T15:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP6_2026_gp",
          "type": "race",
          "startsAt": "2026-06-14T13:00:00Z",
          "endsAt": "2026-06-14T15:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 8,
      "id": "austria",
      "name": {
        "zh": "奥地利大奖赛",
        "en": "Austrian Grand Prix"
      },
      "location": {
        "zh": "施皮尔贝格",
        "en": "Spielberg"
      },
      "coordinates": {
        "latitude": 47.2225,
        "longitude": 14.7607
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP7_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-06-26T11:30:00Z",
          "endsAt": "2026-06-26T12:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP7_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-06-26T15:00:00Z",
          "endsAt": "2026-06-26T16:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP7_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-06-27T10:30:00Z",
          "endsAt": "2026-06-27T11:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP7_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-06-27T14:00:00Z",
          "endsAt": "2026-06-27T15:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP7_2026_gp",
          "type": "race",
          "startsAt": "2026-06-28T13:00:00Z",
          "endsAt": "2026-06-28T15:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 9,
      "id": "great-britain",
      "name": {
        "zh": "英国大奖赛",
        "en": "British Grand Prix"
      },
      "location": {
        "zh": "银石",
        "en": "Silverstone"
      },
      "coordinates": {
        "latitude": 52.0706,
        "longitude": -1.0174
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP8_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-07-03T11:30:00Z",
          "endsAt": "2026-07-03T12:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP8_2026_sprintQualifying",
          "type": "sprint-qualifying",
          "startsAt": "2026-07-03T15:30:00Z",
          "endsAt": "2026-07-03T16:15:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP8_2026_sprint",
          "type": "sprint",
          "startsAt": "2026-07-04T11:00:00Z",
          "endsAt": "2026-07-04T11:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP8_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-07-04T15:00:00Z",
          "endsAt": "2026-07-04T16:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP8_2026_gp",
          "type": "race",
          "startsAt": "2026-07-05T14:00:00Z",
          "endsAt": "2026-07-05T16:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 10,
      "id": "belgium",
      "name": {
        "zh": "比利时大奖赛",
        "en": "Belgian Grand Prix"
      },
      "location": {
        "zh": "斯帕",
        "en": "Spa-Francorchamps"
      },
      "coordinates": {
        "latitude": 50.444,
        "longitude": 5.9687
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP9_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-07-17T11:30:00Z",
          "endsAt": "2026-07-17T12:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP9_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-07-17T15:00:00Z",
          "endsAt": "2026-07-17T16:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP9_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-07-18T10:30:00Z",
          "endsAt": "2026-07-18T11:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP9_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-07-18T14:00:00Z",
          "endsAt": "2026-07-18T15:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP9_2026_gp",
          "type": "race",
          "startsAt": "2026-07-19T13:00:00Z",
          "endsAt": "2026-07-19T15:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 11,
      "id": "hungary",
      "name": {
        "zh": "匈牙利大奖赛",
        "en": "Hungarian Grand Prix"
      },
      "location": {
        "zh": "布达佩斯",
        "en": "Budapest"
      },
      "coordinates": {
        "latitude": 47.583,
        "longitude": 19.2526
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP10_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-07-24T11:30:00Z",
          "endsAt": "2026-07-24T12:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP10_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-07-24T15:00:00Z",
          "endsAt": "2026-07-24T16:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP10_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-07-25T10:30:00Z",
          "endsAt": "2026-07-25T11:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP10_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-07-25T14:00:00Z",
          "endsAt": "2026-07-25T15:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP10_2026_gp",
          "type": "race",
          "startsAt": "2026-07-26T13:00:00Z",
          "endsAt": "2026-07-26T15:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 12,
      "id": "netherlands",
      "name": {
        "zh": "荷兰大奖赛",
        "en": "Dutch Grand Prix"
      },
      "location": {
        "zh": "赞德沃特",
        "en": "Zandvoort"
      },
      "coordinates": {
        "latitude": 52.388408,
        "longitude": 4.547122
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP11_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-08-21T10:30:00Z",
          "endsAt": "2026-08-21T11:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP11_2026_sprintQualifying",
          "type": "sprint-qualifying",
          "startsAt": "2026-08-21T14:30:00Z",
          "endsAt": "2026-08-21T15:15:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP11_2026_sprint",
          "type": "sprint",
          "startsAt": "2026-08-22T10:00:00Z",
          "endsAt": "2026-08-22T10:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP11_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-08-22T14:00:00Z",
          "endsAt": "2026-08-22T15:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP11_2026_gp",
          "type": "race",
          "startsAt": "2026-08-23T13:00:00Z",
          "endsAt": "2026-08-23T15:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 13,
      "id": "italy",
      "name": {
        "zh": "意大利大奖赛",
        "en": "Italian Grand Prix"
      },
      "location": {
        "zh": "蒙扎",
        "en": "Monza"
      },
      "coordinates": {
        "latitude": 45.6169,
        "longitude": 9.2825
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP12_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-09-04T10:30:00Z",
          "endsAt": "2026-09-04T11:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP12_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-09-04T14:00:00Z",
          "endsAt": "2026-09-04T15:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP12_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-09-05T10:30:00Z",
          "endsAt": "2026-09-05T11:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP12_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-09-05T14:00:00Z",
          "endsAt": "2026-09-05T15:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP12_2026_gp",
          "type": "race",
          "startsAt": "2026-09-06T13:00:00Z",
          "endsAt": "2026-09-06T15:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 14,
      "id": "spain",
      "name": {
        "zh": "西班牙大奖赛",
        "en": "Spanish Grand Prix"
      },
      "location": {
        "zh": "马德里",
        "en": "Madrid"
      },
      "coordinates": {
        "latitude": 40.4168,
        "longitude": -3.7038
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP13_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-09-11T11:30:00Z",
          "endsAt": "2026-09-11T12:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP13_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-09-11T15:00:00Z",
          "endsAt": "2026-09-11T16:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP13_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-09-12T10:30:00Z",
          "endsAt": "2026-09-12T11:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP13_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-09-12T14:00:00Z",
          "endsAt": "2026-09-12T15:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP13_2026_gp",
          "type": "race",
          "startsAt": "2026-09-13T13:00:00Z",
          "endsAt": "2026-09-13T15:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 15,
      "id": "azerbaijan",
      "name": {
        "zh": "阿塞拜疆大奖赛",
        "en": "Azerbaijan Grand Prix"
      },
      "location": {
        "zh": "巴库",
        "en": "Baku"
      },
      "coordinates": {
        "latitude": 40.3699,
        "longitude": 49.8433
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP14_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-09-24T08:30:00Z",
          "endsAt": "2026-09-24T09:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP14_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-09-24T12:00:00Z",
          "endsAt": "2026-09-24T13:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP14_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-09-25T08:30:00Z",
          "endsAt": "2026-09-25T09:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP14_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-09-25T12:00:00Z",
          "endsAt": "2026-09-25T13:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP14_2026_gp",
          "type": "race",
          "startsAt": "2026-09-26T11:00:00Z",
          "endsAt": "2026-09-26T13:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 16,
      "id": "bahrain-malaysia-tbc",
      "name": {
        "zh": "巴林大奖赛（马来西亚，待确认）",
        "en": "Bahrain Grand Prix (Malaysia, TBC)"
      },
      "location": {
        "zh": "雪邦",
        "en": "Sepang"
      },
      "coordinates": {
        "latitude": 2.760278,
        "longitude": 101.738056
      },
      "status": "tentative",
      "sessions": [
        {
          "id": "GP15_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-10-02T02:00:00Z",
          "endsAt": "2026-10-02T03:00:00Z",
          "status": "tentative"
        },
        {
          "id": "GP15_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-10-02T06:00:00Z",
          "endsAt": "2026-10-02T07:00:00Z",
          "status": "tentative"
        },
        {
          "id": "GP15_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-10-03T06:00:00Z",
          "endsAt": "2026-10-03T07:00:00Z",
          "status": "tentative"
        },
        {
          "id": "GP15_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-10-03T09:00:00Z",
          "endsAt": "2026-10-03T10:00:00Z",
          "status": "tentative"
        },
        {
          "id": "GP15_2026_gp",
          "type": "race",
          "startsAt": "2026-10-04T07:00:00Z",
          "endsAt": "2026-10-04T09:00:00Z",
          "status": "tentative"
        }
      ]
    },
    {
      "round": 17,
      "id": "singapore",
      "name": {
        "zh": "新加坡大奖赛",
        "en": "Singapore Grand Prix"
      },
      "location": {
        "zh": "新加坡",
        "en": "Singapore"
      },
      "coordinates": {
        "latitude": 1.2857,
        "longitude": 103.8575
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP16_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-10-09T08:30:00Z",
          "endsAt": "2026-10-09T09:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP16_2026_sprintQualifying",
          "type": "sprint-qualifying",
          "startsAt": "2026-10-09T12:30:00Z",
          "endsAt": "2026-10-09T13:15:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP16_2026_sprint",
          "type": "sprint",
          "startsAt": "2026-10-10T09:00:00Z",
          "endsAt": "2026-10-10T09:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP16_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-10-10T13:00:00Z",
          "endsAt": "2026-10-10T14:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP16_2026_gp",
          "type": "race",
          "startsAt": "2026-10-11T12:00:00Z",
          "endsAt": "2026-10-11T14:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 18,
      "id": "united-states",
      "name": {
        "zh": "美国大奖赛",
        "en": "United States Grand Prix"
      },
      "location": {
        "zh": "奥斯汀",
        "en": "Austin"
      },
      "coordinates": {
        "latitude": 30.1328,
        "longitude": -97.6411
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP17_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-10-23T17:30:00Z",
          "endsAt": "2026-10-23T18:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP17_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-10-23T21:00:00Z",
          "endsAt": "2026-10-23T22:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP17_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-10-24T17:30:00Z",
          "endsAt": "2026-10-24T18:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP17_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-10-24T21:00:00Z",
          "endsAt": "2026-10-24T22:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP17_2026_gp",
          "type": "race",
          "startsAt": "2026-10-25T20:00:00Z",
          "endsAt": "2026-10-25T22:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 19,
      "id": "mexico",
      "name": {
        "zh": "墨西哥大奖赛",
        "en": "Mexico City Grand Prix"
      },
      "location": {
        "zh": "墨西哥城",
        "en": "Mexico City"
      },
      "coordinates": {
        "latitude": 19.4028,
        "longitude": -99.0986
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP18_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-10-30T18:30:00Z",
          "endsAt": "2026-10-30T19:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP18_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-10-30T22:00:00Z",
          "endsAt": "2026-10-30T23:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP18_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-10-31T17:30:00Z",
          "endsAt": "2026-10-31T18:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP18_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-10-31T21:00:00Z",
          "endsAt": "2026-10-31T22:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP18_2026_gp",
          "type": "race",
          "startsAt": "2026-11-01T20:00:00Z",
          "endsAt": "2026-11-01T22:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 20,
      "id": "brazil",
      "name": {
        "zh": "巴西大奖赛",
        "en": "São Paulo Grand Prix"
      },
      "location": {
        "zh": "圣保罗",
        "en": "São Paulo"
      },
      "coordinates": {
        "latitude": -23.7014,
        "longitude": -46.6969
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP19_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-11-06T15:30:00Z",
          "endsAt": "2026-11-06T16:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP19_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-11-06T19:00:00Z",
          "endsAt": "2026-11-06T20:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP19_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-11-07T14:30:00Z",
          "endsAt": "2026-11-07T15:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP19_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-11-07T18:00:00Z",
          "endsAt": "2026-11-07T19:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP19_2026_gp",
          "type": "race",
          "startsAt": "2026-11-08T17:00:00Z",
          "endsAt": "2026-11-08T19:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 21,
      "id": "las-vegas",
      "name": {
        "zh": "拉斯维加斯大奖赛",
        "en": "Las Vegas Grand Prix"
      },
      "location": {
        "zh": "拉斯维加斯",
        "en": "Las Vegas"
      },
      "coordinates": {
        "latitude": 36.166747,
        "longitude": -115.148708
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP20_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-11-20T00:30:00Z",
          "endsAt": "2026-11-20T01:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP20_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-11-20T04:00:00Z",
          "endsAt": "2026-11-20T05:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP20_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-11-21T00:30:00Z",
          "endsAt": "2026-11-21T01:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP20_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-11-21T04:00:00Z",
          "endsAt": "2026-11-21T05:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP20_2026_gp",
          "type": "race",
          "startsAt": "2026-11-22T04:00:00Z",
          "endsAt": "2026-11-22T06:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 22,
      "id": "qatar",
      "name": {
        "zh": "卡塔尔大奖赛",
        "en": "Qatar Grand Prix"
      },
      "location": {
        "zh": "多哈",
        "en": "Doha"
      },
      "coordinates": {
        "latitude": 25.490292,
        "longitude": 51.45303
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP21_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-11-27T13:30:00Z",
          "endsAt": "2026-11-27T14:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP21_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-11-27T17:00:00Z",
          "endsAt": "2026-11-27T18:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP21_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-11-28T14:30:00Z",
          "endsAt": "2026-11-28T15:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP21_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-11-28T18:00:00Z",
          "endsAt": "2026-11-28T19:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP21_2026_gp",
          "type": "race",
          "startsAt": "2026-11-29T16:00:00Z",
          "endsAt": "2026-11-29T18:00:00Z",
          "status": "confirmed"
        }
      ]
    },
    {
      "round": 23,
      "id": "abu-dhabi",
      "name": {
        "zh": "阿布扎比大奖赛",
        "en": "Abu Dhabi Grand Prix"
      },
      "location": {
        "zh": "亚斯码头",
        "en": "Yas Marina"
      },
      "coordinates": {
        "latitude": 24.4821,
        "longitude": 54.3482
      },
      "status": "confirmed",
      "sessions": [
        {
          "id": "GP22_2026_fp1",
          "type": "practice-1",
          "startsAt": "2026-12-04T09:30:00Z",
          "endsAt": "2026-12-04T10:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP22_2026_fp2",
          "type": "practice-2",
          "startsAt": "2026-12-04T13:00:00Z",
          "endsAt": "2026-12-04T14:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP22_2026_fp3",
          "type": "practice-3",
          "startsAt": "2026-12-05T10:30:00Z",
          "endsAt": "2026-12-05T11:30:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP22_2026_qualifying",
          "type": "qualifying",
          "startsAt": "2026-12-05T14:00:00Z",
          "endsAt": "2026-12-05T15:00:00Z",
          "status": "confirmed"
        },
        {
          "id": "GP22_2026_gp",
          "type": "race",
          "startsAt": "2026-12-06T13:00:00Z",
          "endsAt": "2026-12-06T15:00:00Z",
          "status": "confirmed"
        }
      ]
    }
  ]
} as const;
