import React from 'react';
import { 
  Folder, Globe, Server, Cpu, Wrench, PlayCircle, 
  Link as LinkIcon, Cloud, Database, Code, Terminal, 
  Home, Star, Zap, Book, Image, Music, Video,
  Settings, User, Calendar, Mail, MessageSquare, ShoppingCart, Heart, Camera, Map, FileText, Monitor, Smartphone, Wifi, Lock,
  Github, Gitlab, Twitter, Instagram, Facebook, Linkedin, Youtube, Twitch, Chrome, Slack, Figma, Dribbble, Codepen, Trello,
  Gamepad, Headphones, Tv, Bitcoin, CreditCard, Wallet, ListTodo, Clock, CheckCircle, Package, Box, Container, HardDrive,
  Bot, Brain, Sparkles, Wand2
} from 'lucide-react';

export const iconMap: Record<string, React.ElementType> = {
  folder: Folder,
  link: LinkIcon,
  globe: Globe,
  server: Server,
  cpu: Cpu,
  tool: Wrench,
  play: PlayCircle,
  cloud: Cloud,
  database: Database,
  code: Code,
  terminal: Terminal,
  home: Home,
  star: Star,
  zap: Zap,
  book: Book,
  image: Image,
  music: Music,
  video: Video,
  settings: Settings,
  user: User,
  calendar: Calendar,
  mail: Mail,
  message: MessageSquare,
  cart: ShoppingCart,
  heart: Heart,
  camera: Camera,
  map: Map,
  file: FileText,
  monitor: Monitor,
  mobile: Smartphone,
  wifi: Wifi,
  lock: Lock,
  github: Github,
  gitlab: Gitlab,
  twitter: Twitter,
  instagram: Instagram,
  facebook: Facebook,
  linkedin: Linkedin,
  youtube: Youtube,
  twitch: Twitch,
  chrome: Chrome,
  slack: Slack,
  figma: Figma,
  dribbble: Dribbble,
  codepen: Codepen,
  trello: Trello,
  gamepad: Gamepad,
  headphones: Headphones,
  tv: Tv,
  bitcoin: Bitcoin,
  creditcard: CreditCard,
  wallet: Wallet,
  todo: ListTodo,
  clock: Clock,
  check: CheckCircle,
  package: Package,
  box: Box,
  container: Container,
  disk: HardDrive,
  bot: Bot,
  brain: Brain,
  sparkles: Sparkles,
  magic: Wand2
};

export const getIcon = (name: string | undefined, isFolder: boolean, size: number, className?: string) => {
    const Icon = iconMap[name || (isFolder ? 'folder' : 'link')] || (isFolder ? Folder : LinkIcon);
    return <Icon size={size} className={className} />;
};
